[programs.localnet]
escrow = "93tkEd8UBH9yWRDnFzppoRkw3CKMz8vV8VmPKir9cXP3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/skywalker/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
